DROP OWNED BY webstack;
REASSIGN OWNED BY webstack TO postgres;
DROP DATABASE webstack;
CREATE DATABASE webstack;

DROP USER webstack;
CREATE USER webstack WITH PASSWORD 'webstack';
GRANT CONNECT ON DATABASE webstack TO webstack;
GRANT USAGE ON SCHEMA public TO webstack;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO webstack;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO webstack;
ALTER USER webstack WITH SUPERUSER;
